config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :sregistrations
  resources :line_items
  resources :carts
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins, :controllers => { registrations: 'registrations' }
  devise_for :students, :controllers => { registrations: 'registrations' }
  devise_for :teachers, :controllers => { registrations: 'registrations' }
  resources :courses
  resources :tregistrations
  resources :histories
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "courses#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    # @course = Course.new
    @course = current_admin.courses.build
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = current_admin.courses.build(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :course_no, :discipline, :area, :price)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="columns is-mobile is-centered">
  <div class="column is-half">
    <%= simple_form_for(@course) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
    <%= f.input :name, label: "Course Name", wrapper: false, label_html: {class: "label"}, placeholder: "Name of the course?", autofocus: true%>
    <%= f.input :course_no, label: "Course Number", wrapper: false, label_html: {class: "label"}, placeholder: "Course Number?", autofocus: true%>
    <%= f.input :discipline, label: "Discipline", wrapper: false, label_html: {class: "label"}, placeholder: "Discipline?", autofocus: true%>
    <%= f.input :area, label: "Area", wrapper: false, label_html: {class: "label"}, placeholder: "Area?", autofocus: true%>
    <%= f.input :price, label: "Price", wrapper: false, label_html: {class: "label"}, placeholder: "Price", autofocus: true%>
    </div>
    <div class="form-actions">
    <%= f.button :submit, class: "button is-primary is-small" %>
    </div>
    <% end %>
  </div>
</div>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Browse the available courses on Athena!
      </h1>
    </div>
  </div>
</section>

<% if student_signed_in? || admin_signed_in? || teacher_signed_in? %>
<% @courses.each do |course| %>
<div class="box">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <p>Course Name: <%= course.name %></p>
        <p>Price: <%= course.price %></p>
        <%= link_to 'Show', course, class: 'button is-warning is-small' %>
        <% if admin_signed_in? %>
          <%= link_to 'Edit', edit_course_path(course), class: 'button is-warning is-small' %>
          <%= link_to 'Delete', course, method: :delete, data: {confirm: "Are you sure?"}, class: 'button is-warning is-small' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>
<% end %>


<div class="container">
  <div class="columns is-centered">
    <% if admin_signed_in? %>
      <%= link_to 'New Course', new_course_path, class: 'button is-warning is-small' %>
    <% end %>
    <% if teacher_signed_in? %>
      <%= link_to 'Registered Courses', tregistration_path(current_teacher.id), class: 'button is-warning is-small' %>
      <br/>
      <p><%= link_to 'Student History', history_path(current_teacher.id), class: 'button is-warning is-small' %></p>
      <br/>
      <p><%= link_to 'Feedback', feedback_path(current_teacher.id), class: 'button is-warning is-small' %></p>
    <% end %>
    <% if student_signed_in? %>
      <p><%= link_to 'Registered Courses', sregistration_path(current_student.id), class: 'button is-warning is-small' %></p>
      <br/>
      <p><%= link_to 'Course History', history_path(current_student.id), class: 'button is-warning is-small' %></p>
      <br/>
      <p><%= link_to 'Feedback', feedback_path(current_student.id), class: 'button is-warning is-small' %></p>
    <% end %>
  </div>
</div>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="section">
<div class="container">
    <div class="columns is-centered">
        <div class="column is-4">
            <h2 class="title is-2"> More on the Course! </h2>
        <div class="field">
	  	    <div class="control">
          <div class="box">
	            <p><strong>Name:</strong> <%= @course.name %></p>
              <p><strong>Course Number: </strong>  <%= @course.course_no %></p>
              <p><strong>Discipline: </strong>  <%= @course.discipline %></p>
              <p><strong>Area: </strong>  <%= @course.area %></p>
              <p><strong>Price: </strong>  <%= @course.price %></p>
              <p><strong>Available teachers: </strong> 
                <% @course.teachers.each do |teacher| %>
                  <p> Dr. <%= teacher.name %> </p>
                  <% if admin_signed_in? %>
                    <p> <%= button_to 'Add to cart', line_items_path(course_id: @course, teacher_id: teacher.id), class: 'button is-warning is-small add-to-cart' %> </p>
                  <% end %>
                  <% if student_signed_in? && current_student.major == @course.discipline %>
                    <p> <%= button_to 'Add to cart', line_items_path(course_id: @course, teacher_id: teacher.id), class: 'button is-warning is-small add-to-cart' %> </p>
                  <% end %>
                <% end %>
              </p>
              <% if teacher_signed_in? %>
                <% if current_teacher.discipline == @course.discipline %>
                  <p> <%= button_to 'Register for this course!', tregistrations_path(course_id: @course, teacher_id: current_teacher.id),  class: 'button is-warning is-small add-to-cart' %>   </p>
                <% end %>
              <% end %>
              <br>
              <%= link_to 'Edit', edit_course_path(@course), class: 'button is-warning is-small'%> |
              <%= link_to 'Back', courses_path, class: 'button is-warning is-small' %>
              </div>
	  	    </div>
		</div>
        </div>
    </div>
</div>
</div>