config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :sregistrations
  resources :line_items
  resources :carts
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins, :controllers => { registrations: 'registrations' }
  devise_for :students, :controllers => { registrations: 'registrations' }
  devise_for :teachers, :controllers => { registrations: 'registrations' }
  resources :courses
  resources :tregistrations
  resources :histories
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "courses#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Athena</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if flash[:notice] %>
  		<div class="notification is-primary global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
  	<% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>
  	<nav class="navbar is-dark">
  		<div class="navbar-brand">
  		<%= link_to root_path, class: "navbar-item" do %>
		  <%= image_tag("elearning_white.png", :alt => "ATHENA - The e-learning hub!") %>
  		<% end %>
			<div class="navbar-burger burger" data-target="navbarExample">
					<span></span>
					<span></span>
					<span></span>
  		</div>
  	 </div>
			<div id="navbarExample" class="navbar-menu">
				<div class="navbar-end">
          			<div class="navbar-item">
						<div class="field is-grouped">
							<% if student_signed_in? || admin_signed_in? || teacher_signed_in? %>
								<% if total_cart_items %>
									<%= link_to cart_path(@cart), class:"navbar-item button is-dark is-inverted" do %>
									<span class="icon is-small">
										<i class="fa fa-shopping-cart"></i>
									</span>
									<span>Cart
										<%= cart_count_over_one %>
									</span>
									<% end %>
								<% end %>
								<% if admin_signed_in? %>
									<div class="navbar-item has-dropdown is-hoverable">
										<%= link_to 'Account', edit_admin_registration_path, class: "navbar-link" %>
										<div class="navbar-dropdown is-right">
											<%= link_to "Admin Panel", rails_admin_path , class:"navbar-item" %>
											<%= link_to current_admin.email.split("@")[0].capitalize, edit_admin_registration_path, class:"navbar-item" %>
											<%= link_to "Log Out", destroy_admin_session_path, method: :delete, class:"navbar-item" %>
										</div>
									</div>
								<% elsif student_signed_in? %>
									<div class="navbar-item has-dropdown is-hoverable">
										<%= link_to 'Account', edit_student_registration_path, class: "navbar-link" %>
										<div class="navbar-dropdown is-right">
											<%= link_to current_student.email.split("@")[0].capitalize, edit_student_registration_path, class:"navbar-item" %>
											<%= link_to "Log Out", destroy_student_session_path, method: :delete, class:"navbar-item" %>
										</div>
									</div>
								<% elsif teacher_signed_in? %>
									<div class="navbar-item has-dropdown is-hoverable">
										<%= link_to 'Account', edit_teacher_registration_path, class: "navbar-link" %>
										<div class="navbar-dropdown is-right">
											<%= link_to current_teacher.email.split("@")[0].capitalize, edit_teacher_registration_path, class:"navbar-item" %>
											<%= link_to "Log Out", destroy_teacher_session_path, method: :delete, class:"navbar-item" %>
										</div>
									</div>
								<% end %>
							<% else %>
							<div class="navbar-item has-dropdown is-hoverable">
								<p class="navbar-link"> Log In</p>
								<div class="navbar-dropdown is-right">
									<%= link_to 'Student Log In', new_student_session_path, class: " navbar-item" %>
									<%= link_to 'Faculty Log In', new_teacher_session_path, class: "navbar-item" %>
									<%= link_to 'Admin Log In', new_admin_session_path, class: "navbar-item" %>
								</div>
							</div>
							<% end %>
				</div>
			</div>
		</div>
		</div>
  	</nav>

    <%= yield %>
  </body>
</html>